# provide solc remappings to crytic-compile
cryticArgs: ['--solc-remaps', '@=node_modules/@']
# 10,000 ether is placed in the NaiveReceiverEchidna contract.
balanceContract: 10000000000000000000000
allContracts: true